# Generated by Django 3.2.10 on 2022-01-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollno', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
                ('Class', models.CharField(max_length=50)),
                ('School', models.CharField(max_length=50)),
                ('Mobile', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
    ]
