# Generated by Django 3.2.10 on 2022-01-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcademics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollno', models.IntegerField()),
                ('Math', models.CharField(max_length=50)),
                ('Physics', models.CharField(max_length=50)),
                ('Chemistry', models.CharField(max_length=50)),
                ('Biology', models.CharField(max_length=50)),
                ('English', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='Mobile',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='Rollno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
