# Generated by Django 4.0.1 on 2022-01-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20220108_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='Mobile',
            field=models.CharField(max_length=10),
        ),
    ]
