# Generated by Django 4.0.1 on 2022-01-08 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_rename_biology_studentacademics_biology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademics',
            name='roll_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enroll.studentinfo'),
        ),
    ]
