# Generated by Django 4.0.1 on 2022-01-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_alter_studentacademics_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademics',
            name='biology',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='chemistry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='english',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='math',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentacademics',
            name='physics',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='class_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='school',
            field=models.CharField(max_length=500),
        ),
    ]
